name: React-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v3

#       - name: install
#         run: npm install
        
#       - name: Test
#         run: npm run test
      - uses: actions/checkout@main
      - name: build
        run: |
          npm install
          npm run test
          npm run deploy
      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}

