name: React-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v3

#       - name: install
#         run: npm install
        
#       - name: Test
#         run: npm run test
      - uses: actions/checkout@main
      - name: build
        run: |
          npm install
          npm run test
          npm run predeploy

